"""boxes table

Revision ID: 58ae553311bf
Revises: 
Create Date: 2021-04-09 22:19:46.812532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ae553311bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('worker', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('tech_task_id', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('tech_task',
    sa.Column('tech_task_id', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('tech_task_id')
    )
    op.create_table('boxes',
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('tech_task_id', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['tech_task_id'], ['tech_task.tech_task_id'], ),
    sa.PrimaryKeyConstraint('box_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boxes')
    op.drop_table('tech_task')
    op.drop_table('logs')
    # ### end Alembic commands ###
